#!/bin/bash

TAG_NAME="Name"
INSTANCE_ID="`wget -qO- http://instance-data/latest/meta-data/instance-id`"
REGION="`wget -qO- http://instance-data/latest/meta-data/placement/availability-zone | sed -e 's:\([0-9][0-9]*\)[a-z]*\$:\\1:'`"
TAG_VALUE="`aws ec2 describe-tags --filters "Name=resource-id,Values=$INSTANCE_ID" "Name=key,Values=$TAG_NAME" --region $REGION --output=text | cut -f5`"

printf "You are in \033[1;34m$REGION\033[0m on instance \033[0;35m$INSTANCE_ID\033[0m\n"
printf "My name is: \033[1;32m$TAG_VALUE\033[0m\n"
